"""Ingest a real working directory into the context-hub knowledge graph.

Designed for production-scale repos:
  • Respects .gitignore and common vendor/build dirs
  • Uses os.walk with pruning (faster than blind rglob on huge trees)
  • Inverted-index-friendly node text (id, name, summary, metadata)
  • Caps function/class nodes per module to bound graph size
  • Indexes markdown/docs as Document nodes linked to nearest service

Hierarchy:
    Repository → Service → Module → Function/Class
    Repository → Document (business docs)
    Repository → Component (declared ids from code_crosswalk.yaml / components.yaml)
    Repository → Requirement/UserStory/TestCase/Epic/Term (ids found in prose)

Edges:
    CONTAINS, DOCUMENTED_BY, IMPORTS, DEPENDS_ON, RELATES_TO (doc↔service mention),
    IMPLEMENTS (Module → Component, from the crosswalk),
    RELATES_TO (artifact → id node, from a `PREFIX-Identifier` mention),
    DEPENDS_ON (TC → US → REQ, declared by a `linked_to` column),
    DEPENDS_ON (Component → Component, Term → Component, declared by a catalog),
    IMPLEMENTS (Component → Endpoint, from `components.yaml exposes:`)

The three structured passes run in a fixed order, and it is load-bearing:
crosswalk → declared catalogs (catalogs.py) → id extraction (idlinks.py) →
declared catalog edges. Declaring nodes before extraction is what stops a
`declared: False` stub being minted for an entity the corpus does declare;
emitting the typed edges after it is what lets them supersede the weaker
`RELATES_TO` mentions covering the same pair.
"""
from __future__ import annotations

import ast
import fnmatch
import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from . import catalogs, idlinks
from .build import est_tokens
from .chunking import DEFAULT_MAX_CHUNKS, TextSpan, chunk_file
from .formats import extract_text, is_indexable_document
from .. import identity
from ..model.schema import Confidence, Edge, EdgeType, Graph, Node, NodeType, Source

IGNORE_DIRS = {
    ".git", "node_modules", ".venv", "venv", "env", "__pycache__", "dist", "build",
    "target", "vendor", ".next", ".nuxt", ".idea", ".vscode", ".pytest_cache",
    ".mypy_cache", ".ruff_cache", "coverage", ".terraform", "bin", "obj", ".gradle",
    "out", "site-packages", "oms_kg", ".repo-kg", ".contexthub", "archive",
    ".tox", ".nox", ".eggs", "*.egg-info", ".cache", "htmlcov", ".pnpm-store",
    "bower_components", ".sass-cache", ".parcel-cache", "tmp", "temp",
}

# Directories that are tool data, not corpus — skipped only at the repo root so
# a legitimate nested `tests/fixtures/` is still indexed. `<root>/fixtures/`
# holds the AIFO/AIFQE datasets the mock adapters serve; indexing it would put
# the tools' own answers into the graph, making "did the model call the tool or
# just read the graph?" unanswerable. `<root>/expected/` holds golden
# questions and expected answers — indexing those would seed retrieval with
# the very text the eval grades against (found live in Phase 9: the sources
# golden file minted CMP-InventoryService, the exact node whose absence is
# the drift signal).
ROOT_ONLY_IGNORE_DIRS = {"fixtures", "expected"}
# Formats that `formats.py` renders as one row per line with `` | `` between
# cells, so a `linked_to` column can be read back out of the extract.
TABULAR_EXTENSIONS = {".csv", ".tsv", ".xlsx", ".xls"}
# workflow-compiler edit: ``.pdf`` is no longer skipped — ``formats.extract_text``
# routes it through ``workflow_compiler.ingestion`` (pypdf).
SKIP_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".svg", ".zip",
    ".tar", ".gz", ".bz2", ".xz", ".7z", ".jar", ".war", ".class", ".o", ".so",
    ".dylib", ".dll", ".exe", ".bin", ".dat", ".db", ".sqlite", ".woff", ".woff2",
    ".ttf", ".eot", ".mp3", ".mp4", ".avi", ".mov", ".min.js", ".min.css",
    ".map", ".lock",
}
GENERATED_MARKERS = (
    "code generated", "auto-generated", "autogenerated", "do not edit",
    "@generated", "GENERATED FILE",
)
MANIFESTS = {
    "package.json", "pyproject.toml", "setup.py", "setup.cfg", "requirements.txt",
    "go.mod", "pom.xml", "build.gradle", "build.gradle.kts", "Cargo.toml",
    "composer.json", "Gemfile", "Dockerfile", "docker-compose.yml", "docker-compose.yaml",
}
README_NAMES = {"readme.md", "readme.rst", "readme.txt", "readme"}
# Directories whose immediate children are one deployable each. Consulted only
# when a repo ships no build manifests at all, so a real polyglot repo is still
# partitioned by `pyproject.toml`/`package.json` rather than by folder naming.
# `codebase` is here for corpora like `sources/`, which keeps 12 services under
# `codebase/<name>/app.py` with no manifest anywhere to discover them by.
SERVICE_HINT_DIRS = {
    "services", "service", "apps", "app", "packages", "package", "codebase",
}
LANG_BY_EXT = {
    ".py": "Python", ".js": "JavaScript", ".jsx": "JavaScript", ".ts": "TypeScript",
    ".tsx": "TypeScript", ".go": "Go", ".java": "Java", ".rb": "Ruby",
    ".rs": "Rust", ".php": "PHP", ".cs": "C#", ".kt": "Kotlin", ".scala": "Scala",
    ".vue": "Vue", ".svelte": "Svelte", ".swift": "Swift", ".m": "Objective-C",
    ".mm": "Objective-C", ".h": "C/C++", ".cpp": "C++", ".c": "C", ".sql": "SQL",
}
MAX_FILE_BYTES = 1_000_000
DEFAULT_MAX_DEFS = 60


@dataclass
class IngestOptions:
    include_functions: bool = True
    max_defs_per_module: int = DEFAULT_MAX_DEFS
    include_chunks: bool = True
    max_chunks_per_file: int = DEFAULT_MAX_CHUNKS
    include_docs: bool = True
    respect_gitignore: bool = True
    cache_dir: Path | None = None
    include_id_links: bool = True
    id_link_options: idlinks.IdLinkOptions | None = None
    include_catalogs: bool = True


def _write_extract(cache_dir: Path, rel: Path, text: str) -> str:
    """Persist extracted text; return path relative to cache_dir parent (.contexthub)."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    safe = rel.as_posix().replace("/", "__")
    out = cache_dir / f"{safe}.txt"
    out.write_text(text, encoding="utf-8")
    return str(out.relative_to(cache_dir.parent))


@dataclass
class _WalkState:
    gitignore_patterns: list[str] = field(default_factory=list)


def _load_gitignore(root: Path) -> list[str]:
    patterns: list[str] = []
    gi = root / ".gitignore"
    if not gi.is_file():
        return patterns
    for line in gi.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            patterns.append(line)
    return patterns


def _ignored_path(rel: Path, patterns: list[str]) -> bool:
    s = rel.as_posix()
    for pat in patterns:
        if fnmatch.fnmatch(s, pat) or fnmatch.fnmatch(s, pat.lstrip("/")):
            return True
        if pat.endswith("/") and s.startswith(pat.rstrip("/")):
            return True
    return False


def _walk(root: Path, *, respect_gitignore: bool = True):
    patterns = _load_gitignore(root) if respect_gitignore else []
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = Path(dirpath).relative_to(root)
        at_root = rel_dir == Path(".")
        dirnames[:] = sorted(
            d for d in dirnames
            if d not in IGNORE_DIRS
            and not (at_root and d in ROOT_ONLY_IGNORE_DIRS)
            and not _ignored_path(rel_dir / d, patterns)
        )
        for name in sorted(filenames):
            path = Path(dirpath) / name
            rel = path.relative_to(root)
            if _ignored_path(rel, patterns):
                continue
            if path.suffix.lower() in SKIP_EXTENSIONS:
                continue
            yield path


def _read(path: Path) -> str:
    try:
        if path.stat().st_size > MAX_FILE_BYTES:
            return ""
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _is_generated(text: str) -> bool:
    head = text[:500].lower()
    return any(m in head for m in GENERATED_MARKERS)


def _readme_summary(text: str, limit: int = 240) -> str:
    for line in text.splitlines():
        s = line.strip().lstrip("#").strip()
        if s and not s.startswith(("![", "[!", "---", "===", "```")):
            return s[:limit]
    return ""


def _doc_summary(text: str, limit: int = 300) -> str:
    for line in text.splitlines():
        s = line.strip().lstrip("#").strip()
        if len(s) > 20 and not s.startswith(("![", "```", "---")):
            return s[:limit]
    return text[:limit].replace("\n", " ")


def _python_defs(text: str) -> tuple[str, list[tuple[str, str, str, int, int]], list[str]]:
    """Return (module_summary, defs, imports).

    Each def is (kind, name, summary, start_line, end_line) with 1-indexed lines.
    """
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return "", [], []
    mod_doc = (ast.get_docstring(tree) or "").splitlines()
    mod_summary = mod_doc[0] if mod_doc else ""
    defs: list[tuple[str, str, str, int, int]] = []
    imports: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            doc = (ast.get_docstring(node) or "").splitlines()
            args = ", ".join(a.arg for a in node.args.args)
            summary = doc[0] if doc else f"def {node.name}({args})"
            start = int(node.lineno)
            if getattr(node, "decorator_list", None):
                start = min(start, min(d.lineno for d in node.decorator_list))
            end = int(getattr(node, "end_lineno", None) or start)
            defs.append(("Function", node.name, summary, start, end))
        elif isinstance(node, ast.ClassDef):
            doc = (ast.get_docstring(node) or "").splitlines()
            summary = doc[0] if doc else f"class {node.name}"
            start = int(node.lineno)
            if getattr(node, "decorator_list", None):
                start = min(start, min(d.lineno for d in node.decorator_list))
            end = int(getattr(node, "end_lineno", None) or start)
            defs.append(("Class", node.name, summary, start, end))
        elif isinstance(node, ast.Import):
            imports.extend(a.name for a in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.level == 0:
                imports.append(node.module)
            elif node.module:
                imports.append("." * node.level + node.module)
    return mod_summary, defs, imports


_RE_DEFS = re.compile(
    r"^\s*(?:export\s+)?(?:public\s+|private\s+|protected\s+|static\s+|async\s+)*"
    r"(?:function|func|def|class|interface|type)\s+([A-Za-z_]\w*)",
    re.MULTILINE,
)
_RE_ARROW = re.compile(r"^\s*(?:export\s+)?const\s+([A-Za-z_]\w*)\s*=\s*(?:async\s*)?\(", re.MULTILINE)
_RE_IMPORT = re.compile(
    r"""(?:import\s+[^'"\n]*from\s+['"]([^'"]+)['"])"""
    r"""|(?:require\(\s*['"]([^'"]+)['"]\s*\))"""
    r"""|(?:import\s+([\w.]+)\s*;)"""
    r"""|(?:^\s*['"]([\w./-]+)['"]\s*$)""",
    re.MULTILINE,
)


def _regex_defs(text: str) -> tuple[str, list[tuple[str, str, str, int, int]], list[str]]:
    defs: list[tuple[str, str, str, int, int]] = []
    for m in _RE_DEFS.finditer(text):
        start = text.count("\n", 0, m.start()) + 1
        end = text.count("\n", 0, m.end()) + 1
        defs.append(("Function", m.group(1), f"{m.group(0).strip()}", start, end))
    for m in _RE_ARROW.finditer(text):
        start = text.count("\n", 0, m.start()) + 1
        end = text.count("\n", 0, m.end()) + 1
        defs.append(("Function", m.group(1), f"const {m.group(1)} = (...)", start, end))
    imports = [g for m in _RE_IMPORT.finditer(text) for g in m.groups() if g]
    return "", defs, imports


def _extract(path: Path, text: str):
    if path.suffix == ".py":
        return _python_defs(text)
    return _regex_defs(text)


def _add_chunk_nodes(
    graph: Graph,
    *,
    parent_id: str,
    rel: Path,
    text: str,
    domain: str,
    extract_rel: str,
    language: str | None = None,
    max_chunks: int = DEFAULT_MAX_CHUNKS,
) -> int:
    """Attach Chunk children + NEXT edges under a Module/Document parent."""
    spans = chunk_file(rel, text, max_chunks=max_chunks)
    if not spans:
        return 0
    prev_id: str | None = None
    for idx, span in enumerate(spans):
        chunk_id = f"chk:{rel}:{idx:03d}"
        name = span.symbol or f"{rel.name}:{span.start_line}-{span.end_line}"
        summary = span.summary or f"lines {span.start_line}-{span.end_line}"
        md: dict = {
            "path": str(rel),
            "repo_path": str(rel),
            "file": str(rel),
            "extract_path": extract_rel,
            "start_line": span.start_line,
            "end_line": span.end_line,
            "chunk_index": idx,
            "kind": span.kind,
            "parent_id": parent_id,
            "extension": rel.suffix.lower(),
        }
        if language:
            md["language"] = language
        if span.symbol:
            md["symbol"] = span.symbol
        graph.add_node(Node(
            chunk_id, NodeType.CHUNK, name, domain=domain,
            summary=summary, summary_tokens=est_tokens(summary),
            metadata=md,
        ))
        graph.add_edge(Edge(EdgeType.CONTAINS, parent_id, chunk_id, source=Source.PARSED))
        if prev_id:
            graph.add_edge(Edge(
                EdgeType.NEXT, prev_id, chunk_id,
                attributes={"order": idx},
                source=Source.PARSED,
            ))
        # Link symbol chunk to matching Function/Class node when present.
        if span.symbol:
            fn_id = f"fn:{rel}:{span.symbol}"
            if fn_id in graph.nodes:
                graph.add_edge(Edge(
                    EdgeType.RELATES_TO, fn_id, chunk_id,
                    attributes={"reason": "symbol_span"},
                    source=Source.PARSED,
                ))
        prev_id = chunk_id
    return len(spans)


def _discover_services(root: Path, files: list[Path]) -> dict[Path, dict]:
    services: dict[Path, dict] = {}
    for f in files:
        if f.name in MANIFESTS:
            d = f.parent
            services.setdefault(d, {"name": d.name if d != root else root.name,
                                    "lang": None, "readme": None})
    if not services:
        for f in files:
            rel = f.relative_to(root)
            if len(rel.parts) >= 2 and rel.parts[0].lower() in SERVICE_HINT_DIRS:
                d = root / rel.parts[0] / rel.parts[1]
                services.setdefault(d, {"name": d.name, "lang": None, "readme": None})
    if not services:
        services[root] = {"name": root.name, "lang": None, "readme": None}
    return services


def _nearest_service(path: Path, service_dirs: list[Path], root: Path) -> Path:
    best = root
    best_len = -1
    for d in service_dirs:
        try:
            path.relative_to(d)
        except ValueError:
            continue
        if len(d.parts) > best_len:
            best, best_len = d, len(d.parts)
    return best


def _is_doc_file(path: Path, root: Path) -> bool:
    return is_indexable_document(path)


def _safe_id(text: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_.:/-]+", "-", text).strip("-")[:160]


def _parse_openapi(text: str) -> tuple[list[dict], list[dict]]:
    try:
        data = json.loads(text) if text.lstrip().startswith("{") else None
    except json.JSONDecodeError:
        data = None
    if data is None:
        try:
            import yaml  # type: ignore
            data = yaml.safe_load(text)
        except Exception:
            data = None
    if not isinstance(data, dict):
        return [], []
    endpoints: list[dict] = []
    schemas: list[dict] = []
    for path, ops in (data.get("paths") or {}).items():
        if not isinstance(ops, dict):
            continue
        for method, spec in ops.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete", "options", "head"}:
                continue
            if not isinstance(spec, dict):
                spec = {}
            endpoints.append({
                "method": method.upper(),
                "path": str(path),
                "name": spec.get("operationId") or f"{method.upper()} {path}",
                "summary": spec.get("summary") or spec.get("description") or f"{method.upper()} {path}",
            })
    components = data.get("components") or {}
    if not isinstance(components, dict):
        components = {}
    schemas_block = components.get("schemas") or {}
    if not isinstance(schemas_block, dict):
        schemas_block = {}
    for name, spec in schemas_block.items():
        fields = []
        if isinstance(spec, dict):
            props = spec.get("properties") or {}
            if isinstance(props, dict):
                fields = list(props.keys())[:20]
        schemas.append({"name": str(name), "fields": fields})
    return endpoints, schemas


def _config_kind(path: Path) -> str | None:
    name = path.name.lower()
    if name in {"docker-compose.yml", "docker-compose.yaml", "dockerfile"}:
        return "container"
    if name.startswith((".github",)):
        return "ci"
    if path.suffix.lower() in {".sql"}:
        return "schema"
    if name in {"package.json", "pyproject.toml", "requirements.txt", "go.mod", "pom.xml", "cargo.toml"}:
        return "manifest"
    if path.suffix.lower() in {".yaml", ".yml", ".json", ".toml"}:
        if any(part.lower() in {".github", "workflows", "k8s", "helm"} for part in path.parts):
            return "infra"
    return None


def _attach_endpoint_and_schema_nodes(
    graph: Graph,
    *,
    owner_id: str,
    owner_domain: str,
    rel: Path,
    endpoints: list[dict],
    schemas: list[dict],
) -> None:
    for ep in endpoints:
        eid = f"ep:{rel}:{_safe_id(ep['method'])}:{_safe_id(ep['path'])}"
        summary = str(ep["summary"])[:240]
        graph.add_node(Node(
            eid, NodeType.ENDPOINT, str(ep["name"]), domain=owner_domain,
            summary=summary, summary_tokens=est_tokens(summary),
            metadata={"path": str(rel), "repo_path": str(rel),
                      "method": ep["method"], "endpoint_path": ep["path"]},
        ))
        graph.add_edge(Edge(EdgeType.IMPLEMENTS, owner_id, eid, source=Source.PARSED))
    for sch in schemas:
        sid = f"schema:{rel}:{_safe_id(sch['name'])}"
        summary = f"Schema {sch['name']}"
        graph.add_node(Node(
            sid, NodeType.SCHEMA, str(sch["name"]), domain=owner_domain,
            summary=summary, summary_tokens=est_tokens(summary),
            metadata={"path": str(rel), "repo_path": str(rel), "fields": sch["fields"]},
        ))
        graph.add_edge(Edge(EdgeType.USES_SCHEMA, owner_id, sid, source=Source.PARSED))


def _attach_component_nodes(
    graph: Graph,
    *,
    root: Path,
    repo_id: str,
    domain: str,
    modules_by_rel: dict[str, str],
) -> int:
    """Turn ``code_crosswalk.yaml`` into Component nodes wired to their code.

    The crosswalk is a declared bridge between two namespaces that otherwise
    never meet in the graph: the ``CMP-*`` ids the docs use and the
    ``codebase/<dir>/`` paths the modules live at.

    Edge direction follows the existing IMPLEMENTS convention (implementer →
    implemented, as Service → Endpoint elsewhere in this file): the module
    implements the component. That also makes the component reachable by an
    upward impact traversal from either end.

    A code directory with no crosswalk row gets no component and no edge. That
    silence is the point — ``sources/codebase/inventory_service/`` is
    undocumented on purpose, as a drift-detection signal.
    """
    path = identity.find_crosswalk(root)
    if path is None:
        return 0
    entries = identity.parse_crosswalk(_read(path))
    if not entries:
        return 0
    cmap = identity.ComponentMap(entries)
    rel_crosswalk = str(path.relative_to(root))

    for entry in entries:
        code_dir = f"{entry.code_path}/"
        summary = f"Component {entry.component_id}, implemented by {code_dir}"
        graph.add_node(Node(
            entry.component_id, NodeType.COMPONENT, entry.component_id, domain=domain,
            summary=summary, summary_tokens=est_tokens(summary),
            metadata={
                "component_id": entry.component_id,
                "code_path": entry.code_path,
                "path": rel_crosswalk,
                "repo_path": rel_crosswalk,
            },
        ))
        graph.add_edge(Edge(EdgeType.CONTAINS, repo_id, entry.component_id,
                            source=Source.PARSED))

    linked = 0
    for rel, mod_id in modules_by_rel.items():
        component_id = cmap.component_for_code_path(rel)
        if component_id is None:
            continue
        graph.add_edge(Edge(
            EdgeType.IMPLEMENTS, mod_id, component_id,
            attributes={"reason": "code_crosswalk"}, source=Source.PARSED,
        ))
        linked += 1
    return linked


def _id_node_index(graph: Graph) -> dict[str, str]:
    """Every id spelling already present in the graph → the node that owns it.

    Shared by the id extractor and the catalog emitter, deliberately: both must
    bind ``API-placeOrder`` to the *same* Endpoint node, and a second
    hand-rolled copy of this lookup is exactly how that invariant would rot.

    Two sources of truth. A node whose type is one an id can name is indexed by
    its own id and by any identifier its metadata declares. Endpoints are also
    indexed by ``operationId``, which is what makes ``components.yaml exposes:
    API-placeOrder`` and the OpenAPI operation one entity rather than two —
    but only when the name is unique across the corpus. An operationId claimed
    by two specs cannot be bound without guessing which was meant, so it is
    left out and mints its own node instead; the ambiguity is worth seeing.
    """
    index: dict[str, str] = {}
    endpoints_by_name: dict[str, list[str]] = {}
    id_types = set(idlinks.NODE_TYPE_BY_PREFIX.values())

    for node in graph.nodes.values():
        if node.type is NodeType.ENDPOINT:
            endpoints_by_name.setdefault(node.name.casefold(), []).append(node.id)
        if node.type not in id_types:
            continue
        index.setdefault(node.id.casefold(), node.id)
        metadata = node.metadata or {}
        for key in ("component_id", "identifier"):
            declared = metadata.get(key)
            if declared:
                index.setdefault(str(declared).casefold(), node.id)

    endpoint_prefixes = [
        p for p, t in idlinks.NODE_TYPE_BY_PREFIX.items() if t is NodeType.ENDPOINT
    ]
    for name, node_ids in endpoints_by_name.items():
        if len(node_ids) == 1:
            for prefix in endpoint_prefixes:
                index.setdefault(f"{prefix}-{name}".casefold(), node_ids[0])
    return index


def _declare_catalog_nodes(
    graph: Graph,
    *,
    root: Path,
    repo_id: str,
    domain: str,
) -> tuple[list[catalogs.Declaration], catalogs.CatalogStats]:
    """Pass A — give every declared component and term a real, *declared* node.

    This runs **before** the id extractor on purpose. ``terms.yaml`` defines
    ``TERM-DeviceFinancing`` with a name and a definition; if the extractor got
    there first it would mint a bare stub carrying ``declared: False`` and the
    summary *"not declared anywhere in this repository"* — which is simply
    false, and it corrupts the one flag the drift narrative depends on. Making
    the declared node first means the extractor *binds* to it, and
    ``declared: False`` keeps meaning what it is supposed to mean: referenced
    somewhere, defined nowhere.

    Components usually already exist, built from the crosswalk, which knows the
    code path but not the display name or the prose description. Those are
    merged in rather than replacing the node, so both halves survive.
    """
    stats = catalogs.CatalogStats()
    declarations: list[catalogs.Declaration] = []

    for filenames, collections, text_fields, ntype in (
        (catalogs.COMPONENT_FILENAMES, catalogs.COMPONENT_COLLECTIONS,
         catalogs.COMPONENT_TEXT_FIELDS, NodeType.COMPONENT),
        (catalogs.TERM_FILENAMES, catalogs.TERM_COLLECTIONS,
         catalogs.TERM_TEXT_FIELDS, NodeType.TERM),
    ):
        path = catalogs.find_catalog(root, filenames)
        if path is None:
            continue
        rel = str(path.relative_to(root))
        rows = catalogs.parse_declarations(
            _read(path), collections=collections,
            text_fields=text_fields, source_file=rel,
        )
        if not rows:
            continue
        declarations.extend(rows)
        if ntype is NodeType.COMPONENT:
            stats.components += len(rows)
        else:
            stats.terms += len(rows)

        for decl in rows:
            node = graph.nodes.get(decl.id)
            if node is None:
                summary = decl.text or f"{ntype.value} {decl.id}"
                graph.add_node(Node(
                    decl.id, ntype, decl.name or decl.id, domain=domain,
                    summary=summary, summary_tokens=est_tokens(summary),
                    metadata={
                        "identifier": decl.id, "id_prefix": idlinks.prefix_of(decl.id),
                        "declared": True, "display_name": decl.name,
                        "description": decl.text,
                        "path": rel, "repo_path": rel,
                    },
                ))
                graph.add_edge(Edge(EdgeType.CONTAINS, repo_id, decl.id,
                                    source=Source.PARSED))
                stats.created += 1
                continue

            # Merge onto whatever the crosswalk (or an earlier pass) already knew.
            if decl.name:
                node.name = decl.name
            if decl.text:
                node.summary = decl.text
                node.summary_tokens = est_tokens(decl.text)
            metadata = dict(node.metadata or {})
            metadata.update({
                "identifier": decl.id, "declared": True,
                "display_name": decl.name, "description": decl.text,
                "declared_in": rel,
            })
            node.metadata = metadata
            stats.enriched += 1

    return declarations, stats


def _attach_catalog_edges(
    graph: Graph,
    *,
    declarations: list[catalogs.Declaration],
    stats: catalogs.CatalogStats,
) -> catalogs.CatalogStats:
    """Pass B — emit the typed, directional edges the catalogs declare.

    Runs **after** the id extractor so every referenced id is guaranteed to
    have a node to point at, whether it was bound to an existing one or minted.

    Phase 4.3's de-duplication is here: a declared relation is a *statement*,
    while the extractor's ``RELATES_TO`` is only evidence that two ids appeared
    near each other. Where both exist for the same pair the weaker one is
    removed, so the graph carries one edge with the strongest available claim
    rather than a typed edge shadowed by a lateral duplicate.

    A target that resolves to no node is counted, not invented. On ``sources/``
    that count is the honest measure of dangling references in the corpus.
    """
    if not declarations:
        return stats
    index = _id_node_index(graph)

    typed: set[tuple[str, str, EdgeType]] = set()
    mention_rows: dict[frozenset[str], list[int]] = {}
    for position, edge in enumerate(graph.edges):
        typed.add((edge.src, edge.dst, edge.type))
        if edge.type is EdgeType.RELATES_TO:
            mention_rows.setdefault(frozenset((edge.src, edge.dst)), []).append(position)

    superseded: set[int] = set()
    for decl in declarations:
        src = index.get(decl.id.casefold(), decl.id)
        if src not in graph.nodes:
            continue
        for _field, etype, reason, target in decl.relations():
            dst = index.get(target.casefold())
            if dst is None or dst not in graph.nodes or dst == src:
                stats.unresolved += dst is None
                continue
            if (src, dst, etype) in typed:
                stats.duplicate += 1
                continue
            graph.add_edge(Edge(
                etype, src, dst,
                attributes={"reason": reason, "via": decl.source_file},
                confidence=Confidence.CONFIRMED, source=Source.PARSED,
            ))
            typed.add((src, dst, etype))
            for position in mention_rows.get(frozenset((src, dst)), ()):
                if position not in superseded:
                    superseded.add(position)
                    stats.replaced_mentions += 1
            stats.typed_edges += 1

    if superseded:
        graph.edges = [e for i, e in enumerate(graph.edges) if i not in superseded]
    graph.build_index()
    return stats


def _attach_id_nodes(
    graph: Graph,
    *,
    repo_id: str,
    domain: str,
    index: idlinks.IdIndex,
) -> idlinks.IdScanStats:
    """Promote every `PREFIX-Identifier` found in prose to a node, and link it.

    Three steps, in this order, because each depends on the last:

    1. **Bind or mint.** An id that already has a node uses it — ``CMP-*`` finds
       the Component the crosswalk declared, ``API-*`` finds the Endpoint
       ``_parse_openapi`` built from a matching ``operationId``. Binding is what
       makes ``components.yaml exposes: API-placeOrder`` and the OpenAPI
       operation the *same* entity. Anything unmatched is minted with
       ``declared: False``, which is a drift signal worth keeping, not a defect.
    2. **Declared links.** ``linked_to`` gives real direction, so those edges are
       laid down first and marked CONFIRMED.
    3. **Mentions.** Everything else is a lateral RELATES_TO, marked INFERRED —
       a document naming an id is evidence of a relationship, not a statement of
       one. A pair already joined by a typed edge is skipped, so the stronger
       claim always wins (this is the de-duplication Phase 4 would otherwise
       have to undo).

    Minting never invents a *declared* component: ``CMP-InventoryService``
    appears nowhere in ``sources/``, so the undocumented service stays
    unresolvable exactly as §2.8 intends.
    """
    kept = index.finalize()
    if not kept:
        return index.stats

    existing = _id_node_index(graph)

    node_for: dict[str, str] = {}
    for identifier in sorted(kept):
        bound = existing.get(identifier.casefold())
        if bound:
            node_for[identifier] = bound
            continue
        prefix = idlinks.prefix_of(identifier)
        ntype = idlinks.NODE_TYPE_BY_PREFIX.get(prefix, NodeType.DATA_ARTIFACT)
        summary = (
            f"{ntype.value} {identifier}, referenced by {len(kept[identifier])} "
            f"artifact(s); not declared anywhere in this repository"
        )
        graph.add_node(Node(
            identifier, ntype, identifier, domain=domain,
            summary=summary, summary_tokens=est_tokens(summary),
            metadata={"identifier": identifier, "id_prefix": prefix, "declared": False},
        ))
        graph.add_edge(Edge(EdgeType.CONTAINS, repo_id, identifier, source=Source.PARSED))
        node_for[identifier] = identifier
        index.stats.minted_nodes += 1

    connected: set[tuple[str, str]] = set()
    for edge in graph.edges:
        connected.add((edge.src, edge.dst))
        connected.add((edge.dst, edge.src))

    semantics = index.options.link_semantics
    for src_id, dst_id in sorted(index.links):
        src, dst = node_for.get(src_id), node_for.get(dst_id)
        if not src or not dst or src == dst or (src, dst) in connected:
            continue
        etype, reason = semantics.get(
            (idlinks.prefix_of(src_id), idlinks.prefix_of(dst_id)), idlinks.FALLBACK_LINK
        )
        graph.add_edge(Edge(
            etype, src, dst, attributes={"reason": reason, "via": "linked_to"},
            source=Source.PARSED,
        ))
        connected.add((src, dst))
        connected.add((dst, src))
        index.stats.link_edges += 1

    for identifier in sorted(kept):
        target = node_for[identifier]
        for artifact in sorted(kept[identifier]):
            if artifact == target or (artifact, target) in connected:
                continue
            graph.add_edge(Edge(
                EdgeType.RELATES_TO, artifact, target,
                attributes={"reason": "id_mention", "identifier": identifier},
                confidence=Confidence.INFERRED, source=Source.PARSED,
            ))
            connected.add((artifact, target))
            connected.add((target, artifact))
            index.stats.mention_edges += 1

    return index.stats


def ingest(
    root: Path,
    *,
    verbose: bool = False,
    include_functions: bool = True,
    max_defs_per_module: int = DEFAULT_MAX_DEFS,
    include_chunks: bool = True,
    max_chunks_per_file: int = DEFAULT_MAX_CHUNKS,
    include_docs: bool = True,
    respect_gitignore: bool = True,
    cache_dir: Path | None = None,
    include_id_links: bool = True,
    id_link_options: idlinks.IdLinkOptions | None = None,
    include_catalogs: bool = True,
) -> Graph:
    root = Path(root).resolve()
    files = list(_walk(root, respect_gitignore=respect_gitignore))
    extract_root = cache_dir or (root / ".contexthub" / "extracts")
    graph = Graph()
    # Scanned inline as files stream past so the extracted text is never all
    # held at once — only the id sets survive each file.
    id_index = idlinks.IdIndex(id_link_options) if include_id_links else None

    repo_id = f"repo:{root.name}"
    repo_readme = next((f for f in files if f.parent == root
                        and f.name.lower() in README_NAMES), None)
    repo_summary = _readme_summary(_read(repo_readme)) if repo_readme else f"Repository {root.name}"
    graph.add_node(Node(repo_id, NodeType.REPOSITORY, root.name, domain=root.name,
                        summary=repo_summary, summary_tokens=est_tokens(repo_summary),
                        metadata={"path": str(root)}))

    services = _discover_services(root, files)
    service_dirs = sorted(services.keys(), key=lambda p: len(p.parts), reverse=True)

    svc_id_by_dir: dict[Path, str] = {}
    for d, info in services.items():
        rel = "." if d == root else str(d.relative_to(root))
        svc_id = f"svc:{rel}"
        svc_id_by_dir[d] = svc_id
        readme = next((f for f in files if f.parent == d
                       and f.name.lower() in README_NAMES), None)
        summary = _readme_summary(_read(readme)) if readme else f"Service {info['name']}"
        graph.add_node(Node(
            svc_id, NodeType.SERVICE, info["name"], domain=info["name"],
            summary=summary, summary_tokens=est_tokens(summary),
            metadata={"path": rel, "repo_path": rel}))
        graph.add_edge(Edge(EdgeType.CONTAINS, repo_id, svc_id))
        if readme:
            doc_id = f"doc:{readme.relative_to(root)}"
            graph.add_node(Node(doc_id, NodeType.DOCUMENT, readme.name, domain=info["name"],
                                summary=summary, summary_tokens=est_tokens(summary),
                                metadata={"path": str(readme.relative_to(root))}))
            graph.add_edge(Edge(EdgeType.DOCUMENTED_BY, svc_id, doc_id, source=Source.PARSED))

    module_index: dict[str, str] = {}
    module_service: dict[str, str] = {}
    module_imports: dict[str, list[str]] = {}
    modules_by_rel: dict[str, str] = {}

    source_files = [f for f in files if LANG_BY_EXT.get(f.suffix) and not _is_generated(_read(f)[:600])]
    source_paths = {f.resolve() for f in source_files}
    doc_files = [
        f for f in files
        if include_docs and _is_doc_file(f, root)
        and f.name.lower() not in README_NAMES
        and f.resolve() not in source_paths
    ]

    for f in source_files:
        lang = LANG_BY_EXT[f.suffix]
        rel = f.relative_to(root)
        text = _read(f)
        if not text:
            continue
        svc_dir = _nearest_service(f, service_dirs, root)
        svc_id = svc_id_by_dir.get(svc_dir, repo_id)
        svc_name = services[svc_dir]["name"] if svc_dir in services else root.name
        if services.get(svc_dir) and services[svc_dir]["lang"] is None:
            services[svc_dir]["lang"] = lang

        mod_id = f"mod:{rel}"
        mod_summary, defs, imports = _extract(f, text)
        mod_summary = mod_summary or f"{lang} module {f.name}"
        extract_rel = _write_extract(extract_root, rel, text)
        graph.add_node(Node(mod_id, NodeType.MODULE, str(rel), domain=svc_name,
                            summary=mod_summary, summary_tokens=est_tokens(mod_summary),
                            metadata={"language": lang, "path": str(rel), "repo_path": str(rel),
                                      "loc": text.count("\n") + 1, "extension": f.suffix.lower(),
                                      "extract_path": extract_rel, "content_chars": len(text)}))
        graph.add_edge(Edge(EdgeType.CONTAINS, svc_id, mod_id))
        cfg_kind = _config_kind(f)
        if cfg_kind:
            cfg_id = f"cfg:{rel}"
            cfg_summary = f"{cfg_kind.title()} config {f.name}"
            graph.add_node(Node(
                cfg_id, NodeType.CONFIG, f.name, domain=svc_name,
                summary=cfg_summary, summary_tokens=est_tokens(cfg_summary),
                metadata={"path": str(rel), "repo_path": str(rel), "kind": cfg_kind,
                          "extract_path": extract_rel},
            ))
            graph.add_edge(Edge(EdgeType.READS_CONFIG, svc_id, cfg_id, source=Source.PARSED))

        stem = str(rel.with_suffix(""))
        module_index[stem] = mod_id
        module_index[stem.replace("/", ".")] = mod_id
        module_index.setdefault(f.stem, mod_id)
        module_service[mod_id] = svc_id
        module_imports[mod_id] = imports
        modules_by_rel[str(rel)] = mod_id
        if id_index is not None:
            id_index.scan(mod_id, text)

        if include_functions:
            for kind, name, summary, start, end in defs[:max_defs_per_module]:
                fn_id = f"fn:{rel}:{name}"
                ntype = NodeType.CLASS if kind == "Class" else NodeType.FUNCTION
                graph.add_node(Node(fn_id, ntype, name, domain=svc_name,
                                    summary=summary, summary_tokens=est_tokens(summary),
                                    metadata={
                                        "file": str(rel), "path": str(rel),
                                        "start_line": start, "end_line": end,
                                    }))
                graph.add_edge(Edge(EdgeType.CONTAINS, mod_id, fn_id))

        if include_chunks:
            _add_chunk_nodes(
                graph,
                parent_id=mod_id,
                rel=rel,
                text=text,
                domain=svc_name,
                extract_rel=extract_rel,
                language=lang,
                max_chunks=max_chunks_per_file,
            )

    for f in doc_files:
        rel = f.relative_to(root)
        text = extract_text(f)
        if not text or len(text.strip()) < 10:
            continue
        svc_dir = _nearest_service(f, service_dirs, root)
        svc_name = services[svc_dir]["name"] if svc_dir in services else root.name
        doc_id = f"doc:{rel}"
        if doc_id in graph.nodes:
            continue
        extract_rel = _write_extract(extract_root, rel, text)
        summary = _doc_summary(text)
        graph.add_node(Node(
            doc_id, NodeType.DOCUMENT, f.name, domain=svc_name,
            summary=summary, summary_tokens=est_tokens(summary),
            metadata={
                "path": str(rel), "repo_path": str(rel),
                "extension": f.suffix.lower(),
                "extract_path": extract_rel,
                "content_chars": len(text),
            },
        ))
        svc_id = svc_id_by_dir.get(svc_dir, repo_id)
        graph.add_edge(Edge(EdgeType.DOCUMENTED_BY, svc_id, doc_id, source=Source.PARSED))
        graph.add_edge(Edge(EdgeType.CONTAINS, repo_id, doc_id))
        if id_index is not None:
            id_index.scan(doc_id, text, tabular=f.suffix.lower() in TABULAR_EXTENSIONS)
        if include_chunks:
            _add_chunk_nodes(
                graph,
                parent_id=doc_id,
                rel=rel,
                text=text,
                domain=svc_name,
                extract_rel=extract_rel,
                max_chunks=max_chunks_per_file,
            )
        endpoints, schemas = ([], [])
        if "openapi" in f.name.lower() or f.suffix.lower() in {".yaml", ".yml", ".json"}:
            endpoints, schemas = _parse_openapi(text)
        if endpoints or schemas:
            md = dict(graph.nodes[doc_id].metadata or {})
            md["doc_type"] = md.get("doc_type") or "openapi"
            graph.nodes[doc_id].metadata = md
            _attach_endpoint_and_schema_nodes(
                graph, owner_id=svc_id, owner_domain=svc_name, rel=rel,
                endpoints=endpoints, schemas=schemas,
            )
        cfg_kind = _config_kind(f)
        if cfg_kind:
            cfg_id = f"cfg:{rel}"
            cfg_summary = f"{cfg_kind.title()} config {f.name}"
            graph.add_node(Node(
                cfg_id, NodeType.CONFIG, f.name, domain=svc_name,
                summary=cfg_summary, summary_tokens=est_tokens(cfg_summary),
                metadata={"path": str(rel), "repo_path": str(rel), "kind": cfg_kind,
                          "extract_path": extract_rel},
            ))
            graph.add_edge(Edge(EdgeType.READS_CONFIG, svc_id, cfg_id, source=Source.PARSED))

    dep_pairs: set[tuple[str, str]] = set()
    for mod_id, imports in module_imports.items():
        src_svc = module_service[mod_id]
        for imp in imports:
            target = _resolve_import(imp, mod_id, module_index)
            if not target or target == mod_id:
                continue
            graph.add_edge(Edge(EdgeType.IMPORTS, mod_id, target, source=Source.STATIC))
            dst_svc = module_service.get(target)
            if dst_svc and dst_svc != src_svc and (src_svc, dst_svc) not in dep_pairs:
                dep_pairs.add((src_svc, dst_svc))
                graph.add_edge(Edge(EdgeType.DEPENDS_ON, src_svc, dst_svc,
                                    attributes={"reason": "import"}, source=Source.STATIC))

    linked_components = _attach_component_nodes(
        graph, root=root, repo_id=repo_id, domain=root.name,
        modules_by_rel=modules_by_rel,
    )

    # Pass A: declared components and terms become real nodes *before* the
    # extractor runs, so it binds to them instead of minting `declared: False`
    # stubs for entities this repo demonstrably declares.
    declarations: list[catalogs.Declaration] = []
    catalog_stats = None
    if include_catalogs:
        declarations, catalog_stats = _declare_catalog_nodes(
            graph, root=root, repo_id=repo_id, domain=root.name,
        )

    id_stats = None
    if id_index is not None:
        # After the components exist, so `CMP-*` binds to them instead of
        # minting a rival node for the same entity.
        id_stats = _attach_id_nodes(
            graph, repo_id=repo_id, domain=root.name, index=id_index,
        )

    # Pass B: the declared edges, last, so every id they reference already has
    # a node — bound or minted — and the de-duplication can see every mention.
    if catalog_stats is not None:
        _attach_catalog_edges(graph, declarations=declarations, stats=catalog_stats)

    # workflow-compiler edit: node ids and path metadata are OS-independent.
    _normalise_posix(graph)

    graph.build_index()
    if verbose:
        extra = f", {linked_components} modules bridged to components" if linked_components else ""
        if id_stats and id_stats.ids_kept:
            extra += f", {id_stats.summary()}"
        if catalog_stats and catalog_stats.typed_edges:
            extra += f", {catalog_stats.summary()}"
        print(f"  scanned {len(files)} files, {len(source_files)} source, "
              f"{len(doc_files)} docs under {root}{extra}")
    return graph


_PATH_METADATA_KEYS = ("path", "repo_path", "file", "extract_path", "declared_in")


def _posix(value: str) -> str:
    return value.replace("\\", "/")


def _normalise_posix(graph: Graph) -> None:
    """Rewrite node ids, module names and path metadata to ``/`` separators.

    workflow-compiler edit. Upstream builds ids like ``mod:src\\pkg\\mod.py`` on
    Windows, which makes a graph built on one OS undereferenceable on another
    and makes ids differ between developers' machines. Ids are rewritten in
    place, edges re-pointed, and the adjacency index rebuilt by the caller.
    """
    renames: dict[str, str] = {}
    for old_id, node in list(graph.nodes.items()):
        new_id = _posix(old_id)
        md = node.metadata
        if md:
            for key in _PATH_METADATA_KEYS:
                val = md.get(key)
                if isinstance(val, str) and "\\" in val:
                    md[key] = _posix(val)
        if "\\" in node.name and node.type in (NodeType.MODULE, NodeType.CHUNK,
                                               NodeType.FUNCTION, NodeType.CLASS):
            node.name = _posix(node.name)
        if new_id != old_id:
            renames[old_id] = new_id
            node.id = new_id
    if not renames:
        return
    for old_id, new_id in renames.items():
        node = graph.nodes.pop(old_id)
        graph.nodes.setdefault(new_id, node)
    for edge in graph.edges:
        if edge.src in renames:
            edge.src = renames[edge.src]
        if edge.dst in renames:
            edge.dst = renames[edge.dst]
    graph._indexed = False


def _resolve_import(imp: str, src_mod_id: str, index: dict[str, str]) -> str | None:
    if imp.startswith("."):
        src_rel = Path(src_mod_id[len("mod:"):])
        base = src_rel.parent
        up = len(imp) - len(imp.lstrip("."))
        for _ in range(max(up - 1, 0)):
            base = base.parent
        target = (base / imp.lstrip(".").replace(".", "/")).as_posix()
        return index.get(target) or index.get(Path(target).name)
    candidates = [imp, imp.replace(".", "/"), imp.split(".")[-1], imp.split("/")[-1]]
    for c in candidates:
        if c in index:
            return index[c]
    return None
