import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const FPS = 30;
const PAD = 0.7; // tail hold after narration ends
const FOOT = path.resolve("../video/public/footage");
const VO = path.resolve("../video/public/vo");
const OUT = path.resolve("../video/src/config.ts");

// name = footage/vo filename base; vo = narration filename base; trim = head seconds to skip
const ORDER = [
  { name: "hero", vo: "intro", trim: 1.2 },
  { name: "login", vo: "login", trim: 0.9 },
  { name: "create", vo: "create", trim: 1.6 },
  { name: "spec", vo: "spec", trim: 1.8 },
  { name: "edit", vo: "edit", trim: 1.8 },
  { name: "editrequest", vo: "editrequest", trim: 1.8 },
  { name: "results", vo: "results", trim: 1.8 },
  { name: "metrics", vo: "metrics", trim: 1.8 },
  { name: "config", vo: "config", trim: 1.6 },
  { name: "docs", vo: "docs", trim: 1.4 },
  { name: "outro", vo: "outro", trim: 1.2 },
];

const dur = (f) =>
  parseFloat(execFileSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", f]).toString().trim());

const scenes = [];
for (const s of ORDER) {
  const fpath = path.join(FOOT, `${s.name}.webm`);
  const vpath = path.join(VO, `${s.vo}.mp3`);
  if (!fs.existsSync(fpath)) { console.error("MISSING footage", s.name); continue; }
  const footageDur = dur(fpath);
  const voDur = fs.existsSync(vpath) ? dur(vpath) : 4;
  const sceneSec = voDur + PAD;
  // clamp trim so trim + sceneSec fits inside footage
  let trim = Math.min(s.trim, Math.max(0, footageDur - sceneSec - 0.05));
  let usableSec = footageDur - trim;
  if (usableSec < sceneSec) { trim = 0; usableSec = footageDur; } // footage short: will slow to fill
  scenes.push({
    name: s.name, vo: s.vo,
    durationInFrames: Math.round(sceneSec * FPS),
    usableSec: +usableSec.toFixed(3),
    trimFrames: Math.round(trim * FPS),
    _foot: +footageDur.toFixed(2), _vo: +voDur.toFixed(2),
  });
}

const total = scenes.reduce((a, s) => a + s.durationInFrames, 0);
console.log("scenes:");
for (const s of scenes) console.log(`  ${s.name.padEnd(12)} vo=${s._vo}s foot=${s._foot}s -> ${s.durationInFrames}f trim=${s.trimFrames}f usable=${s.usableSec}s`);
console.log(`TOTAL ${total}f = ${(total / FPS).toFixed(1)}s (${Math.floor(total/FPS/60)}:${String(Math.round(total/FPS%60)).padStart(2,"0")})`);

const body = `// AUTO-GENERATED by demo/capture2/generate-config.mjs — do not edit by hand.
export type SceneCfg = {
  name: string;
  vo: string;
  durationInFrames: number;
  usableSec: number;
  trimFrames: number;
};

export const FPS = ${FPS};

export const SCENES: SceneCfg[] = ${JSON.stringify(
  scenes.map(({ _foot, _vo, ...s }) => s), null, 2)};

export const TOTAL = SCENES.reduce((a, s) => a + s.durationInFrames, 0);
`;
fs.writeFileSync(OUT, body);
console.log("wrote", OUT);
