// AUTO-GENERATED by demo/capture2/generate-config.mjs — do not edit by hand.
export type SceneCfg = {
  name: string;
  vo: string;
  durationInFrames: number;
  usableSec: number;
  trimFrames: number;
};

export const FPS = 30;

export const SCENES: SceneCfg[] = [
  {
    "name": "hero",
    "vo": "intro",
    "durationInFrames": 470,
    "usableSec": 12.6,
    "trimFrames": 0
  },
  {
    "name": "login",
    "vo": "login",
    "durationInFrames": 174,
    "usableSec": 5.858,
    "trimFrames": 23
  },
  {
    "name": "create",
    "vo": "create",
    "durationInFrames": 637,
    "usableSec": 23,
    "trimFrames": 48
  },
  {
    "name": "spec",
    "vo": "spec",
    "durationInFrames": 571,
    "usableSec": 14.52,
    "trimFrames": 0
  },
  {
    "name": "edit",
    "vo": "edit",
    "durationInFrames": 520,
    "usableSec": 19.4,
    "trimFrames": 54
  },
  {
    "name": "editrequest",
    "vo": "editrequest",
    "durationInFrames": 475,
    "usableSec": 12.88,
    "trimFrames": 0
  },
  {
    "name": "results",
    "vo": "results",
    "durationInFrames": 532,
    "usableSec": 20.64,
    "trimFrames": 54
  },
  {
    "name": "metrics",
    "vo": "metrics",
    "durationInFrames": 248,
    "usableSec": 7.84,
    "trimFrames": 0
  },
  {
    "name": "config",
    "vo": "config",
    "durationInFrames": 265,
    "usableSec": 10.32,
    "trimFrames": 48
  },
  {
    "name": "docs",
    "vo": "docs",
    "durationInFrames": 206,
    "usableSec": 9.44,
    "trimFrames": 42
  },
  {
    "name": "outro",
    "vo": "outro",
    "durationInFrames": 217,
    "usableSec": 4.84,
    "trimFrames": 0
  }
];

export const TOTAL = SCENES.reduce((a, s) => a + s.durationInFrames, 0);
